export default {
	GET_MEMBER_LIST_REQUEST: 'GET_MEMBER_LIST_REQUEST',
	GET_MEMBER_LIST_SUCCESS: 'GET_MEMBER_LIST_SUCCESS',
	GET_MEMBER_LIST_FAILURE: 'GET_MEMBER_LIST_FAILURE',

	GET_CHAT_LIST_REQUEST: 'GET_CHAT_LIST_REQUEST',
	GET_CHAT_LIST_SUCCESS: 'GET_CHAT_LIST_SUCCESS',
	GET_CHAT_LIST_FAILURE: 'GET_CHAT_LIST_FAILURE',

	SET_USER_CHAT: 'SET_USER_CHAT',
};
